### ISSUE TITLE
KTOR support

### ISSUE THREAD

**Issue by tjerkw** [OpenFolder/kotlin-asyncapi#59]
Nice product. Considering KTOR support? 

I am looking for something that creates a spec from data classes from input / output.. Similar to Python FastAPI

**Comment by lorenzsimon** [comment]
Ktor is definitely on the list. However, one should first extract some of the common logic (like annotation scanning) from the Spring Boot module.
I won't have time for it soon, but someone else could pick it up and I can review it.

**Comment by mankra** [comment]
I've seen that the KTor support is already in the 3.0.4 prerelease version. Do you have any idea about the release date of this version?

**Comment by lorenzsimon** [comment]
@mankra sorry for the very long release cycle 😓. We migrated to project to asyncapi and I did not get the Maven deployment to work yet. I am actively working on a fix now and Ktor support will be included in the next release 3.0.4.

**Comment by mankra** [comment]
This is great to hear! Thank you for the quick reply.
